version: "3.8"
services:
    mysql:
        image: mysql:5.7.38
        container_name: app-db
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db:/var/lib/mysql
        ports:
            - "3306:3306"
volumes:
    db:
        name: "app-db"
